### ISSUE TITLE
Reproducible crash with Farming bag

### ISSUE THREAD

**Issue by DoctorVanGogh** [DeviatorTX/SpecializedBags#1]
I know you're not keeping any source here, but  - yay - dedicated issue tracker 😁 

I can crash the game *reliably* with your mod.

Swap out an empty specialized bag (Farming Bag) with another specialized bag (Mining Bag) picked up from a container.
**Crash** 😕 

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)04.04.2021 02:20:12: Critical error occurred
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
```

Video demonstration:
https://youtu.be/m_SWgBUF6VM

--- 
Looking at the stack trace it doesn't look like anything particular from *your* mod and it might just be that your "new" use case of _other_ specialized bags exposes an underlying bug in the VS gui code 😉

**Comment by DoctorVanGogh** [comment]
Addition:

Crash does *not* happen if the inventory (E) is closed during the swap.

**Comment by DeviatorTX** [comment]
> 
> 
> Addition:
> 
> Crash does _not_ happen if the inventory (E) is closed during the swap.

I was able to reproduce even if the bags had items in them. Also, it didn't matter if the bags came from the player inventory hot bar or a container. It looks like it might have something to do with the gui code trying to render the swapped slots but not updating the slotId's, though I am not a coder so it's really just a guess at this point. Will keep looking into it, thanks for pointing it out.

**Comment by DeviatorTX** [comment]
Did some more testing, changing the inventory slot colors to match the mining bag fixed the problem. There is something in the VS code that causes the crash when trying to swap 2 slots of different colors.
